name: Node.js CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      working-directory: ./frontend
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
